server:
  port: 8080
  servlet:
    context-path:
    encoding:
      charset: UTF-8

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations: file:media, classpath:/static
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB

  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  #  rabbitmq:
  #    host: localhost # rabbitMQ host (docker로 띄웠음)
  #    port: 5672 # default port
  #    username: guest # default username
  #    password: guest # default password
  data:
    redis:
      port: 6379
      host: 127.0.0.1


jwt:
  secret: ${JWT_SECRET}
  accessExpirationTime: ${JWT_EXPIRATION}

NAVER_MAP_CLIENT_ID: ${NAVER_MAP_ID}
NAVER_MAP_CLIENT_SECRET: ${NAMER_MAP_SECRET}